
package br.com.mystudies.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://jaxws.mystudies.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operation", targetNamespace = "http://jaxws.mystudies.com.br/", className = "br.com.mystudies.jaxws.Operation")
    @ResponseWrapper(localName = "operationResponse", targetNamespace = "http://jaxws.mystudies.com.br/", className = "br.com.mystudies.jaxws.OperationResponse")
    public String operation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
